### Pobierz losową liczbę Int
GET http://localhost:3000/randomInt

### Pobierz losową liczbę Float
GET http://localhost:3000/randomDouble

### Pobierz losowe pary
GET http://localhost:3000/randomPairs